# Generated by Django 4.2.14 on 2024-07-17 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    7,
                    17,
                    12,
                    37,
                    37,
                    312680,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    7,
                    17,
                    12,
                    37,
                    37,
                    312680,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
