# Generated by Django 4.2.14 on 2024-07-17 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0003_remove_user_groups_remove_user_is_superuser_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_hash",
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    7,
                    17,
                    13,
                    51,
                    50,
                    504408,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
